#!/usr/bin/env python3
"""
145 торгуемых символов для TradeGPT Scalper
Топ монеты по объему и ликвидности на Bybit Futures
"""

TRADING_SYMBOLS_145 = [
    'BTCUSDT',
    'ETHUSDT',
    'BNBUSDT',
    'XRPUSDT',
    'SOLUSDT',
    'ADAUSDT',
    'DOGEUSDT',
    'DOTUSDT',
    'MATICUSDT',
    'AVAXUSDT',
    'LINKUSDT',
    'UNIUSDT',
    'LTCUSDT',
    'BCHUSDT',
    'ATOMUSDT',
    'ETCUSDT',
    'XLMUSDT',
    'NEARUSDT',
    'APTUSDT',
    'ARBUSDT',
    'OPUSDT',
    'SUIUSDT',
    'TIAUSDT',
    'SEIUSDT',
    'INJUSDT',
    'FTMUSDT',
    'ALGOUSDT',
    'VETUSDT',
    'FILUSDT',
    'ICPUSDT',
    'HBARUSDT',
    'APEUSDT',
    'SANDUSDT',
    'MANAUSDT',
    'AXSUSDT',
    'GALAUSDT',
    'THETAUSDT',
    'RUNEUSDT',
    'FLRUSDT',
    'AAVEUSDT',
    'CRVUSDT',
    'MKRUSDT',
    'SNXUSDT',
    'COMPUSDT',
    'YFIUSDT',
    'SUSHIUSDT',
    '1INCHUSDT',
    'BALUSDT',
    'ZRXUSDT',
    'LDOUSDT',
    'RPLUSDT',
    'BLURUSDT',
    'IMXUSDT',
    'DYDXUSDT',
    'GMXUSDT',
    'GNSUSDT',
    'PERPUSDT',
    'MAGICUSDT',
    'RDNTUSDT',
    'METISUSDT',
    'ENJUSDT',
    'CHZUSDT',
    'FLOWUSDT',
    'ILVUSDT',
    'ALICEUSDT',
    'TLMUSDT',
    'SLPUSDT',
    'YGGUSDT',
    'GHSTUSDT',
    'SUPERUSDT',
    'VOXELUSDT',
    'HIGHUSDT',
    'NAKAUSDT',
    'PYRUSDT',
    'WAXPUSDT',
    'STARLUSDT',
    'GODSUSDT',
    'TOWERUSDT',
    'SIDUSUSDT',
    'HEROUSDT',
    'GRTUSDT',
    'OCEANUSDT',
    'ARUSDT',
    'STORJUSDT',
    'ANKRUSDT',
    'LPTUSDT',
    'RNDRUSDT',
    'ROSEUSDT',
    'SKLUSDT',
    'CTSIUSDT',
    'API3USDT',
    'BANDUSDT',
    'NKNUSDT',
    'CELRUSDT',
    'COTIUSDT',
    'IOTXUSDT',
    'JASMYUSDT',
    'AGIXUSDT',
    'FETUSDT',
    'OCEANUSDT',
    'SHIBUSDT',
    'PEPEUSDT',
    'FLOKIUSDT',
    'BONKUSDT',
    'WIFUSDT',
    'MEMEUSDT',
    'DOGE2USDT',
    'BABYDOGEUSDT',
    'ELONUSDT',
    'SAMOUSDT',
    'MYROUSDT',
    'WENUSDT',
    'BOMEUSDT',
    'SLERFUSDT',
    'MUMUUSDT',
    'POPCATUSDT',
    'MOGUSDT',
    'BRETTUSDT',
    'TURBOUSDT',
    'WOJAKUSDT',
    'JUPUSDT',
    'PYTHUSDT',
    'WLDUSDT',
    'STRKUSDT',
    'MANTAUSDT',
    'DYMUSDT',
    'ALTUSDT',
    'PORTALUSDT',
    'PIXELUSDT',
    'AEVOUSDT',
    'XAIUSDT',
    'MAVIAUSDT',
    'RONINUSDT',
    'SAGAUSDT',
    'OMNIUSDT',
    'MERLUSDT',
    'REZUSDT',
    'BLASTUSDT',
    'EIGENUSDT',
    'ZETAUSDT',
    'ZKUSDT',
    'LISTAUSDT',
    'IOUSDT',
    'NOTUSDT',
    'TONUSDT'
]


def get_symbols():
    """Получить список символов"""
    return TRADING_SYMBOLS_145

def get_symbols_count():
    """Получить количество символов"""
    return len(TRADING_SYMBOLS_145)

if __name__ == '__main__':
    print(f"Всего символов: {get_symbols_count()}")
    print(f"Первые 10: {TRADING_SYMBOLS_145[:10]}")
    print(f"Последние 10: {TRADING_SYMBOLS_145[-10:]}")
