#!/usr/bin/env python3
"""
145 торгуемых символов для TradeGPT Scalper
Топ монеты по объему и ликвидности на Bybit Futures
"""

TRADING_SYMBOLS_145 = [
    # Top 20 - Major coins
    'BTC/USDT:USDT', 'ETH/USDT:USDT', 'BNB/USDT:USDT', 'XRP/USDT:USDT',
    'SOL/USDT:USDT', 'ADA/USDT:USDT', 'DOGE/USDT:USDT', 'DOT/USDT:USDT',
    'MATIC/USDT:USDT', 'AVAX/USDT:USDT', 'LINK/USDT:USDT', 'UNI/USDT:USDT',
    'LTC/USDT:USDT', 'BCH/USDT:USDT', 'ATOM/USDT:USDT', 'ETC/USDT:USDT',
    'XLM/USDT:USDT', 'NEAR/USDT:USDT', 'APT/USDT:USDT', 'ARB/USDT:USDT',
    
    # 21-40 - High volume altcoins
    'OP/USDT:USDT', 'SUI/USDT:USDT', 'TIA/USDT:USDT', 'SEI/USDT:USDT',
    'INJ/USDT:USDT', 'FTM/USDT:USDT', 'ALGO/USDT:USDT', 'VET/USDT:USDT',
    'FIL/USDT:USDT', 'ICP/USDT:USDT', 'HBAR/USDT:USDT', 'APE/USDT:USDT',
    'SAND/USDT:USDT', 'MANA/USDT:USDT', 'AXS/USDT:USDT', 'GALA/USDT:USDT',
    'THETA/USDT:USDT', 'RUNE/USDT:USDT', 'FLR/USDT:USDT', 'AAVE/USDT:USDT',
    
    # 41-60 - DeFi & Layer 2
    'CRV/USDT:USDT', 'MKR/USDT:USDT', 'SNX/USDT:USDT', 'COMP/USDT:USDT',
    'YFI/USDT:USDT', 'SUSHI/USDT:USDT', '1INCH/USDT:USDT', 'BAL/USDT:USDT',
    'ZRX/USDT:USDT', 'LDO/USDT:USDT', 'RPL/USDT:USDT', 'BLUR/USDT:USDT',
    'IMX/USDT:USDT', 'DYDX/USDT:USDT', 'GMX/USDT:USDT', 'GNS/USDT:USDT',
    'PERP/USDT:USDT', 'MAGIC/USDT:USDT', 'RDNT/USDT:USDT', 'METIS/USDT:USDT',
    
    # 61-80 - Gaming & Metaverse
    'ENJ/USDT:USDT', 'CHZ/USDT:USDT', 'FLOW/USDT:USDT', 'ILV/USDT:USDT',
    'ALICE/USDT:USDT', 'TLM/USDT:USDT', 'SLP/USDT:USDT', 'YGG/USDT:USDT',
    'GHST/USDT:USDT', 'SUPER/USDT:USDT', 'VOXEL/USDT:USDT', 'HIGH/USDT:USDT',
    'NAKA/USDT:USDT', 'PYR/USDT:USDT', 'WAXP/USDT:USDT', 'STARL/USDT:USDT',
    'GODS/USDT:USDT', 'TOWER/USDT:USDT', 'SIDUS/USDT:USDT', 'HERO/USDT:USDT',
    
    # 81-100 - Infrastructure & Storage
    'GRT/USDT:USDT', 'OCEAN/USDT:USDT', 'AR/USDT:USDT', 'STORJ/USDT:USDT',
    'ANKR/USDT:USDT', 'LPT/USDT:USDT', 'RNDR/USDT:USDT', 'ROSE/USDT:USDT',
    'SKL/USDT:USDT', 'CTSI/USDT:USDT', 'API3/USDT:USDT', 'BAND/USDT:USDT',
    'NKN/USDT:USDT', 'CELR/USDT:USDT', 'COTI/USDT:USDT', 'IOTX/USDT:USDT',
    'JASMY/USDT:USDT', 'AGIX/USDT:USDT', 'FET/USDT:USDT', 'OCEAN/USDT:USDT',
    
    # 101-120 - Meme & Community
    'SHIB/USDT:USDT', 'PEPE/USDT:USDT', 'FLOKI/USDT:USDT', 'BONK/USDT:USDT',
    'WIF/USDT:USDT', 'MEME/USDT:USDT', 'DOGE2/USDT:USDT', 'BABYDOGE/USDT:USDT',
    'ELON/USDT:USDT', 'SAMO/USDT:USDT', 'MYRO/USDT:USDT', 'WEN/USDT:USDT',
    'BOME/USDT:USDT', 'SLERF/USDT:USDT', 'MUMU/USDT:USDT', 'POPCAT/USDT:USDT',
    'MOG/USDT:USDT', 'BRETT/USDT:USDT', 'TURBO/USDT:USDT', 'WOJAK/USDT:USDT',
    
    # 121-145 - New & Trending
    'JUP/USDT:USDT', 'PYTH/USDT:USDT', 'WLD/USDT:USDT', 'STRK/USDT:USDT',
    'MANTA/USDT:USDT', 'DYM/USDT:USDT', 'ALT/USDT:USDT', 'PORTAL/USDT:USDT',
    'PIXEL/USDT:USDT', 'AEVO/USDT:USDT', 'XAI/USDT:USDT', 'MAVIA/USDT:USDT',
    'RONIN/USDT:USDT', 'SAGA/USDT:USDT', 'OMNI/USDT:USDT', 'MERL/USDT:USDT',
    'REZ/USDT:USDT', 'BLAST/USDT:USDT', 'EIGEN/USDT:USDT', 'ZETA/USDT:USDT',
    'ZK/USDT:USDT', 'LISTA/USDT:USDT', 'IO/USDT:USDT', 'NOT/USDT:USDT',
    'TON/USDT:USDT'
]

def get_symbols():
    """Получить список символов"""
    return TRADING_SYMBOLS_145

def get_symbols_count():
    """Получить количество символов"""
    return len(TRADING_SYMBOLS_145)

if __name__ == '__main__':
    print(f"Всего символов: {get_symbols_count()}")
    print(f"Первые 10: {TRADING_SYMBOLS_145[:10]}")
    print(f"Последние 10: {TRADING_SYMBOLS_145[-10:]}")
